const products = [
  {
    title: "Wireless Headphones",
    category: "Electronics",
    price: 79.99,
    img: "https://via.placeholder.com/150?text=Wireless+Headphones",
  },
  {
    title: "Yoga Mat",
    category: "Sports",
    price: 25.5,
    img: "https://via.placeholder.com/150?text=Yoga+Mat",
  },
  {
    title: "Coffee Maker",
    category: "Home Appliances",
    price: 129.99,
    img: "https://via.placeholder.com/150?text=Coffee+Maker",
  },
  {
    title: "Graphic T-Shirt",
    category: "Clothing",
    price: 19.99,
    img: "https://via.placeholder.com/150?text=Graphic+T-Shirt",
  },
  {
    title: "Smartphone Case",
    category: "Electronics",
    price: 15.99,
    img: "https://via.placeholder.com/150?text=Smartphone+Case",
  },
  {
    title: "Dumbbells Set",
    category: "Sports",
    price: 45.0,
    img: "https://via.placeholder.com/150?text=Dumbbells+Set",
  },
  {
    title: "Air Fryer",
    category: "Home Appliances",
    price: 99.0,
    img: "https://via.placeholder.com/150?text=Air+Fryer",
  },
  {
    title: "Hoodie",
    category: "Clothing",
    price: 34.99,
    img: "https://via.placeholder.com/150?text=Hoodie",
  },
  {
    title: "Bluetooth Speaker",
    category: "Electronics",
    price: 59.99,
    img: "https://via.placeholder.com/150?text=Bluetooth+Speaker",
  },
  {
    title: "Running Shoes",
    category: "Sports",
    price: 85.0,
    img: "https://via.placeholder.com/150?text=Running+Shoes",
  },
  {
    title: "Toaster",
    category: "Home Appliances",
    price: 40.0,
    img: "https://via.placeholder.com/150?text=Toaster",
  },
  {
    title: "Jeans",
    category: "Clothing",
    price: 49.99,
    img: "https://via.placeholder.com/150?text=Jeans",
  },
  {
    title: "Wireless Mouse",
    category: "Electronics",
    price: 24.99,
    img: "https://via.placeholder.com/150?text=Wireless+Mouse",
  },
  {
    title: "Fitness Tracker",
    category: "Sports",
    price: 95.0,
    img: "https://via.placeholder.com/150?text=Fitness+Tracker",
  },
  {
    title: "Microwave Oven",
    category: "Home Appliances",
    price: 150.0,
    img: "https://via.placeholder.com/150?text=Microwave+Oven",
  },
  {
    title: "Jacket",
    category: "Clothing",
    price: 79.99,
    img: "https://via.placeholder.com/150?text=Jacket",
  },
  {
    title: "Smart TV",
    category: "Electronics",
    price: 499.99,
    img: "https://via.placeholder.com/150?text=Smart+TV",
  },
  {
    title: "Bicycle",
    category: "Sports",
    price: 250.0,
    img: "https://via.placeholder.com/150?text=Bicycle",
  },
  {
    title: "Blender",
    category: "Home Appliances",
    price: 60.0,
    img: "https://via.placeholder.com/150?text=Blender",
  },
  {
    title: "Sweater",
    category: "Clothing",
    price: 55.99,
    img: "https://via.placeholder.com/150?text=Sweater",
  },
  {
    title: "Tablet",
    category: "Electronics",
    price: 299.99,
    img: "https://via.placeholder.com/150?text=Tablet",
  },
  {
    title: "Football",
    category: "Sports",
    price: 30.0,
    img: "https://via.placeholder.com/150?text=Football",
  },
  {
    title: "Vacuum Cleaner",
    category: "Home Appliances",
    price: 180.0,
    img: "https://via.placeholder.com/150?text=Vacuum+Cleaner",
  },
  {
    title: "T-Shirt",
    category: "Clothing",
    price: 14.99,
    img: "https://via.placeholder.com/150?text=T-Shirt",
  },
  {
    title: "Laptop",
    category: "Electronics",
    price: 899.99,
    img: "https://via.placeholder.com/150?text=Laptop",
  },
  {
    title: "Basketball",
    category: "Sports",
    price: 25.0,
    img: "https://via.placeholder.com/150?text=Basketball",
  },
  {
    title: "Iron",
    category: "Home Appliances",
    price: 45.99,
    img: "https://via.placeholder.com/150?text=Iron",
  },
  {
    title: "Shorts",
    category: "Clothing",
    price: 24.99,
    img: "https://via.placeholder.com/150?text=Shorts",
  },
  {
    title: "E-Book Reader",
    category: "Electronics",
    price: 129.99,
    img: "https://via.placeholder.com/150?text=E-Book+Reader",
  },
  {
    title: "Tennis Racket",
    category: "Sports",
    price: 75.0,
    img: "https://via.placeholder.com/150?text=Tennis+Racket",
  },
];

export default products;
