const products = [
  {
    title: "Electric Toothbrush",
    category: "Home Appliances",
    price: 49.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Electric+Toothbrush",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Rechargeable electric toothbrush with soft bristles.",
    stock: 100,
    ratings: {
      average: 4.5,
      count: 320,
    },
    specifications: {
      color: "White",
      batteryLife: "2 weeks",
      weight: "100 g",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Smart Thermostat",
    category: "Home Appliances",
    price: 119.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Smart+Thermostat",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description:
      "Wi-Fi thermostat with app control for convenient temperature management.",
    stock: 60,
    ratings: {
      average: 4.6,
      count: 260,
    },
    specifications: {
      color: "Gray",
      batteryLife: "N/A",
      weight: "200 g",
      bluetooth: "Yes",
    },
    isAvailable: true,
  },
  {
    title: "Yoga Mat",
    category: "Sports",
    price: 29.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Yoga+Mat",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Non-slip yoga mat perfect for any workout or meditation.",
    stock: 150,
    ratings: {
      average: 4.7,
      count: 390,
    },
    specifications: {
      color: "Purple",
      batteryLife: "N/A",
      weight: "500 g",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Running Shoes",
    category: "Clothing",
    price: 69.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Running+Shoes",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Lightweight and breathable running shoes for all terrain.",
    stock: 80,
    ratings: {
      average: 4.4,
      count: 450,
    },
    specifications: {
      color: "Blue",
      batteryLife: "N/A",
      weight: "300 g",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Electric Kettle",
    category: "Home Appliances",
    price: 39.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Electric+Kettle",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Fast-boiling electric kettle with auto shut-off.",
    stock: 70,
    ratings: {
      average: 4.8,
      count: 500,
    },
    specifications: {
      color: "Stainless Steel",
      batteryLife: "N/A",
      weight: "1 kg",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Dumbbell Set",
    category: "Sports",
    price: 49.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Dumbbell+Set",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Adjustable dumbbell set for versatile home workouts.",
    stock: 90,
    ratings: {
      average: 4.5,
      count: 600,
    },
    specifications: {
      color: "Black",
      batteryLife: "N/A",
      weight: "20 kg",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Smart Oven",
    category: "Home Appliances",
    price: 199.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Smart+Oven",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description:
      "Compact smart oven with multiple cooking modes and app control.",
    stock: 30,
    ratings: {
      average: 4.3,
      count: 120,
    },
    specifications: {
      color: "Black",
      batteryLife: "N/A",
      weight: "8 kg",
      bluetooth: "Yes",
    },
    isAvailable: true,
  },
  {
    title: "Bluetooth Earbuds",
    category: "Electronics",
    price: 59.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Bluetooth+Earbuds",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Compact wireless earbuds with noise-cancellation feature.",
    stock: 100,
    ratings: {
      average: 4.7,
      count: 320,
    },
    specifications: {
      color: "White",
      batteryLife: "6 hours",
      weight: "20 g",
      bluetooth: "5.1",
    },
    isAvailable: true,
  },
  {
    title: "Winter Jacket",
    category: "Clothing",
    price: 99.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Winter+Jacket",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Warm and waterproof jacket for extreme weather.",
    stock: 40,
    ratings: {
      average: 4.8,
      count: 220,
    },
    specifications: {
      color: "Navy",
      batteryLife: "N/A",
      weight: "1.2 kg",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Electric Grill",
    category: "Home Appliances",
    price: 79.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Electric+Grill",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Electric grill for indoor barbecuing and grilling.",
    stock: 60,
    ratings: {
      average: 4.5,
      count: 180,
    },
    specifications: {
      color: "Black",
      batteryLife: "N/A",
      weight: "3 kg",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Robot Vacuum Cleaner",
    category: "Home Appliances",
    price: 199.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Robot+Vacuum+Cleaner",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Automated vacuum cleaner with smart navigation.",
    stock: 25,
    ratings: {
      average: 4.6,
      count: 290,
    },
    specifications: {
      color: "White",
      batteryLife: "90 minutes",
      weight: "2.5 kg",
      bluetooth: "Yes",
    },
    isAvailable: true,
  },
  {
    title: "Electric Hand Mixer",
    category: "Home Appliances",
    price: 24.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Electric+Hand+Mixer",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Compact hand mixer for easy baking and cooking.",
    stock: 85,
    ratings: {
      average: 4.4,
      count: 340,
    },
    specifications: {
      color: "Red",
      batteryLife: "N/A",
      weight: "800 g",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Waterproof Sports Watch",
    category: "Sports",
    price: 49.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Waterproof+Sports+Watch",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Durable sports watch with water resistance and stopwatch.",
    stock: 60,
    ratings: {
      average: 4.5,
      count: 220,
    },
    specifications: {
      color: "Black",
      batteryLife: "2 years",
      weight: "70 g",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Smart Jump Rope",
    category: "Sports",
    price: 29.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Smart+Jump+Rope",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Jump rope with built-in counter and app sync.",
    stock: 90,
    ratings: {
      average: 4.3,
      count: 190,
    },
    specifications: {
      color: "Gray",
      batteryLife: "6 months",
      weight: "150 g",
      bluetooth: "Yes",
    },
    isAvailable: true,
  },
  {
    title: "Wireless Charging Mouse Pad",
    category: "Electronics",
    price: 34.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Charging+Mouse+Pad",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Mouse pad with built-in wireless charging for devices.",
    stock: 50,
    ratings: {
      average: 4.6,
      count: 260,
    },
    specifications: {
      color: "Black",
      batteryLife: "N/A",
      weight: "300 g",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "LED Desk Lamp",
    category: "Electronics",
    price: 19.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=LED+Desk+Lamp",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Adjustable LED desk lamp with touch controls.",
    stock: 120,
    ratings: {
      average: 4.8,
      count: 420,
    },
    specifications: {
      color: "White",
      batteryLife: "N/A",
      weight: "500 g",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Insulated Running Jacket",
    category: "Clothing",
    price: 59.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Running+Jacket",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Lightweight insulated jacket for cold-weather runs.",
    stock: 70,
    ratings: {
      average: 4.5,
      count: 310,
    },
    specifications: {
      color: "Gray",
      batteryLife: "N/A",
      weight: "400 g",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Electric Rice Cooker",
    category: "Home Appliances",
    price: 29.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Rice+Cooker",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Easy-to-use rice cooker with keep-warm function.",
    stock: 100,
    ratings: {
      average: 4.4,
      count: 230,
    },
    specifications: {
      color: "Silver",
      batteryLife: "N/A",
      weight: "2 kg",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Smart Air Purifier",
    category: "Home Appliances",
    price: 149.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Air+Purifier",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Air purifier with HEPA filter and smartphone control.",
    stock: 40,
    ratings: {
      average: 4.7,
      count: 180,
    },
    specifications: {
      color: "White",
      batteryLife: "N/A",
      weight: "4 kg",
      bluetooth: "Yes",
    },
    isAvailable: true,
  },
  {
    title: "Men's Hiking Boots",
    category: "Clothing",
    price: 89.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Hiking+Boots",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Durable, waterproof hiking boots for rugged terrain.",
    stock: 60,
    ratings: {
      average: 4.6,
      count: 280,
    },
    specifications: {
      color: "Brown",
      batteryLife: "N/A",
      weight: "1.5 kg",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Portable Bluetooth Speaker",
    category: "Electronics",
    price: 39.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Bluetooth+Speaker",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Compact, water-resistant speaker with deep bass.",
    stock: 90,
    ratings: {
      average: 4.6,
      count: 480,
    },
    specifications: {
      color: "Black",
      batteryLife: "10 hours",
      weight: "300 g",
      bluetooth: "5.0",
    },
    isAvailable: true,
  },
  {
    title: "Smart Body Scale",
    category: "Electronics",
    price: 29.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Smart+Body+Scale",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Body scale with app integration and health metrics tracking.",
    stock: 75,
    ratings: {
      average: 4.5,
      count: 350,
    },
    specifications: {
      color: "White",
      batteryLife: "6 months",
      weight: "1 kg",
      bluetooth: "Yes",
    },
    isAvailable: true,
  },
  {
    title: "Compression Socks",
    category: "Clothing",
    price: 14.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Compression+Socks",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Comfortable compression socks for sports and recovery.",
    stock: 200,
    ratings: {
      average: 4.8,
      count: 210,
    },
    specifications: {
      color: "Black",
      batteryLife: "N/A",
      weight: "50 g",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Adjustable Dumbbell",
    category: "Sports",
    price: 89.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Adjustable+Dumbbell",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Space-saving dumbbell with adjustable weight settings.",
    stock: 45,
    ratings: {
      average: 4.7,
      count: 290,
    },
    specifications: {
      color: "Black",
      batteryLife: "N/A",
      weight: "20 kg",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Electric Pressure Cooker",
    category: "Home Appliances",
    price: 79.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Pressure+Cooker",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Multi-functional pressure cooker for fast and easy meals.",
    stock: 65,
    ratings: {
      average: 4.8,
      count: 510,
    },
    specifications: {
      color: "Stainless Steel",
      batteryLife: "N/A",
      weight: "5 kg",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Running Leggings",
    category: "Clothing",
    price: 24.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Running+Leggings",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description:
      "Moisture-wicking leggings designed for comfort and performance.",
    stock: 150,
    ratings: {
      average: 4.6,
      count: 380,
    },
    specifications: {
      color: "Black",
      batteryLife: "N/A",
      weight: "200 g",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Heated Blanket",
    category: "Home Appliances",
    price: 59.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Heated+Blanket",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Electric blanket with adjustable heat settings.",
    stock: 40,
    ratings: {
      average: 4.5,
      count: 410,
    },
    specifications: {
      color: "Gray",
      batteryLife: "N/A",
      weight: "2 kg",
      bluetooth: "No",
    },
    isAvailable: true,
  },
  {
    title: "Smartwatch with GPS",
    category: "Electronics",
    price: 99.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Smartwatch",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "GPS-enabled smartwatch with fitness tracking.",
    stock: 70,
    ratings: {
      average: 4.4,
      count: 330,
    },
    specifications: {
      color: "Black",
      batteryLife: "48 hours",
      weight: "80 g",
      bluetooth: "Yes",
    },
    isAvailable: true,
  },
  {
    title: "Wireless Mouse",
    category: "Electronics",
    price: 19.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Wireless+Mouse",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description: "Ergonomic wireless mouse with adjustable DPI settings.",
    stock: 110,
    ratings: {
      average: 4.3,
      count: 260,
    },
    specifications: {
      color: "Black",
      batteryLife: "6 months",
      weight: "100 g",
      bluetooth: "Yes",
    },
    isAvailable: true,
  },
  {
    title: "Insulated Water Bottle",
    category: "Sports",
    price: 14.99,
    currency: "USD",
    img: "https://via.placeholder.com/150?text=Water+Bottle",
    id: `prod_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    description:
      "Durable, double-walled water bottle to keep drinks cold or hot.",
    stock: 90,
    ratings: {
      average: 4.7,
      count: 480,
    },
    specifications: {
      color: "Blue",
      batteryLife: "N/A",
      weight: "500 g",
      bluetooth: "No",
    },
    isAvailable: true,
  },
];

export default products;
